#ifndef _GNM_TYPES_H_
#define _GNM_TYPES_H_

#include <stdbool.h>
#include <stdint.h>

#define GNM_INDIRECT_BUFFER_MAX_BYTESIZE 0x3ffffc
#define GNM_ALIGNMENT_BUFFER_BYTES 4
#define GNM_ALIGNMENT_SHADER_BYTES 256
#define GNM_ALIGNMENT_FETCHSHADER_BYTES 4

#define GNM_NUM_SHADER_STAGES 8
#define GNM_MAX_TSHARP_USERDATA_SLOTS 8
#define GNM_MAX_SSHARP_USERDATA_SLOTS 12
#define GNM_MAX_VSHARP_USERDATA_SLOTS 12
#define GNM_MAX_POINTER_USERDATA_SLOTS 14
#define GNM_MAX_RENDERTARGETS 8
#define GNM_MAX_VIEWPORTS 16

typedef enum {
	// color render targets
	GNM_ACQUIRE_TARGET_CB0 = 0x00000040,
	GNM_ACQUIRE_TARGET_CB1 = 0x00000080,
	GNM_ACQUIRE_TARGET_CB2 = 0x00000100,
	GNM_ACQUIRE_TARGET_CB3 = 0x00000200,
	GNM_ACQUIRE_TARGET_CB4 = 0x00000400,
	GNM_ACQUIRE_TARGET_CB5 = 0x00000800,
	GNM_ACQUIRE_TARGET_CB6 = 0x00001000,
	GNM_ACQUIRE_TARGET_CB7 = 0x00002000,
	// depth render target
	GNM_ACQUIRE_TARGET_DB = 0x00004000,
} GnmAcquireTargetFlags;

typedef enum {
	GNM_ARRAY_LINEAR_GENERAL = 0x0,
	GNM_ARRAY_LINEAR_ALIGNED = 0x1,
	GNM_ARRAY_1D_TILED_THIN1 = 0x2,
	GNM_ARRAY_1D_TILED_THICK = 0x3,
	GNM_ARRAY_2D_TILED_THIN1 = 0x4,
	GNM_ARRAY_PRT_TILED_THIN1 = 0x5,
	GNM_ARRAY_PRT_2D_TILED_THIN1 = 0x6,
	GNM_ARRAY_2D_TILED_THICK = 0x7,
	GNM_ARRAY_2D_TILED_XTHICK = 0x8,
	GNM_ARRAY_PRT_TILED_THICK = 0x9,
	GNM_ARRAY_PRT_2D_TILED_THICK = 0xa,
	GNM_ARRAY_PRT_3D_TILED_THIN1 = 0xb,
	GNM_ARRAY_3D_TILED_THIN1 = 0xc,
	GNM_ARRAY_3D_TILED_THICK = 0xd,
	GNM_ARRAY_3D_TILED_XTHICK = 0xe,
	GNM_ARRAY_PRT_3D_TILED_THICK = 0xf,
} GnmArrayMode;

typedef enum {
	GNM_SURF_BANK_WIDTH_1 = 0x0,
	GNM_SURF_BANK_WIDTH_2 = 0x1,
	GNM_SURF_BANK_WIDTH_4 = 0x2,
	GNM_SURF_BANK_WIDTH_8 = 0x3,
} GnmBankWidth;

typedef enum {
	GNM_SURF_BANK_HEIGHT_1 = 0x0,
	GNM_SURF_BANK_HEIGHT_2 = 0x1,
	GNM_SURF_BANK_HEIGHT_4 = 0x2,
	GNM_SURF_BANK_HEIGHT_8 = 0x3,
} GnmBankHeight;

typedef enum {
	GNM_BLEND_ZERO = 0x0,
	GNM_BLEND_ONE = 0x1,
	GNM_BLEND_SRC_COLOR = 0x2,
	GNM_BLEND_ONE_MINUS_SRC_COLOR = 0x3,
	GNM_BLEND_SRC_ALPHA = 0x4,
	GNM_BLEND_ONE_MINUS_SRC_ALPHA = 0x5,
	GNM_BLEND_DEST_ALPHA = 0x6,
	GNM_BLEND_ONE_MINUS_DEST_ALPHA = 0x7,
	GNM_BLEND_DEST_COLOR = 0x8,
	GNM_BLEND_ONE_MINUS_DEST_COLOR = 0x9,
	GNM_BLEND_SRC_ALPHA_SATURATE = 0xa,
	GNM_BLEND_CONSTANT_COLOR = 0xd,
	GNM_BLEND_ONE_MINUS_CONSTANT_COLOR = 0xe,
	GNM_BLEND_SRC1_COLOR = 0xf,
	GNM_BLEND_INVERSE_SRC1_COLOR = 0x10,
	GNM_BLEND_SRC1_ALPHA = 0x11,
	GNM_BLEND_INVERSE_SRC1_ALPHA = 0x12,
	GNM_BLEND_CONSTANT_ALPHA = 0x13,
	GNM_BLEND_ONE_MINUS_CONSTANT_ALPHA = 0x14,
} GnmBlendOp;

typedef enum {
	GNM_BORDER_COLOR_TRANS_BLACK = 0x0,
	GNM_BORDER_COLOR_OPAQUE_BLACK = 0x1,
	GNM_BORDER_COLOR_OPAQUE_WHITE = 0x2,
	GNM_BORDER_COLOR_FROM_TABLE = 0x3,
} GnmBorderColor;

typedef enum {
	GNM_BUF_DATA_FORMAT_INVALID = 0x0,
	GNM_BUF_DATA_FORMAT_8 = 0x1,
	GNM_BUF_DATA_FORMAT_16 = 0x2,
	GNM_BUF_DATA_FORMAT_8_8 = 0x3,
	GNM_BUF_DATA_FORMAT_32 = 0x4,
	GNM_BUF_DATA_FORMAT_16_16 = 0x5,
	GNM_BUF_DATA_FORMAT_10_11_11 = 0x6,
	GNM_BUF_DATA_FORMAT_11_11_10 = 0x7,
	GNM_BUF_DATA_FORMAT_10_10_10_2 = 0x8,
	GNM_BUF_DATA_FORMAT_2_10_10_10 = 0x9,
	GNM_BUF_DATA_FORMAT_8_8_8_8 = 0xa,
	GNM_BUF_DATA_FORMAT_32_32 = 0xb,
	GNM_BUF_DATA_FORMAT_16_16_16_16 = 0xc,
	GNM_BUF_DATA_FORMAT_32_32_32 = 0xd,
	GNM_BUF_DATA_FORMAT_32_32_32_32 = 0xe,
	GNM_BUF_DATA_FORMAT_RESERVED_15 = 0xf,
} GnmBufferFormat;

typedef enum {
	GNM_BUF_NUM_FORMAT_UNORM = 0x0,
	GNM_BUF_NUM_FORMAT_SNORM = 0x1,
	GNM_BUF_NUM_FORMAT_USCALED = 0x2,
	GNM_BUF_NUM_FORMAT_SSCALED = 0x3,
	GNM_BUF_NUM_FORMAT_UINT = 0x4,
	GNM_BUF_NUM_FORMAT_SINT = 0x5,
	GNM_BUF_NUM_FORMAT_SNORM_OGL = 0x6,
	GNM_BUF_NUM_FORMAT_FLOAT = 0x7,
} GnmBufNumFormat;

typedef enum {
	GNM_POLICY_LRU = 0x0,
	GNM_POLICY_STREAM = 0x1,
	GNM_POLICY_BYPASS = 0x2,
	GNM_POLICY_RESERVED = 0x3,
} GnmCachePolicy;

typedef enum {
	GNM_CHAN_CONSTANT0 = 0x0,
	GNM_CHAN_CONSTANT1 = 0x1,
	GNM_CHAN_X = 0x4,
	GNM_CHAN_Y = 0x5,
	GNM_CHAN_Z = 0x6,
	GNM_CHAN_W = 0x7,
} GnmChannel;

typedef enum {
	GNM_COMB_DST_PLUS_SRC = 0x0,
	GNM_COMB_SRC_MINUS_DST = 0x1,
	GNM_COMB_MIN_DST_SRC = 0x2,
	GNM_COMB_MAX_DST_SRC = 0x3,
	GNM_COMB_DST_MINUS_SRC = 0x4,
} GnmCombFunc;

typedef enum {
	GNM_CULL_NONE = 0x0,
	GNM_CULL_FRONT = 0x1,
	GNM_CULL_BACK = 0x2,
	GNM_CULL_FRONTBACK = 0x3,
} GnmCullMode;

typedef enum {
	GNM_DCC_CT_AUTO = 0x0,
	GNM_DCC_CT_NONE = 0x1,
	GNM_DCC_CT_ABGR = 0x2,
	GNM_DCC_CT_BGRA = 0x3,
} GnmDccColorTransform;

typedef enum {
	GNM_DCC_MBS_64 = 0x0,
	GNM_DCC_MBS_128 = 0x1,
	GNM_DCC_MBS_256 = 0x2,
} GnmDccMaxBlockSize;

typedef enum {
	GNM_DEPTH_COMPARE_NEVER = 0x0,
	GNM_DEPTH_COMPARE_LESS = 0x1,
	GNM_DEPTH_COMPARE_EQUAL = 0x2,
	GNM_DEPTH_COMPARE_LESSEQUAL = 0x3,
	GNM_DEPTH_COMPARE_GREATER = 0x4,
	GNM_DEPTH_COMPARE_NOTEQUAL = 0x5,
	GNM_DEPTH_COMPARE_GREATEREQUAL = 0x6,
	GNM_DEPTH_COMPARE_ALWAYS = 0x7,
} GnmDepthCompare;

typedef struct {
	uint32_t indexCount;
	uint32_t instanceCount;
	uint32_t firstIndex;
	int32_t vertexOffset;
	uint32_t firstInstance;
} GnmDrawIndexedIndirectArgs;
_Static_assert(sizeof(GnmDrawIndexedIndirectArgs) == 0x14, "");

typedef struct {
	uint32_t vertexCount;
	uint32_t instanceCount;
	uint32_t firstVertex;
	uint32_t firstInstance;
} GnmDrawIndirectArgs;
_Static_assert(sizeof(GnmDrawIndirectArgs) == 0x10, "");

typedef struct {
	uint32_t rendertargetsliceoffset : 3;
	uint32_t _unused : 29;
} GnmDrawModifier;
_Static_assert(sizeof(GnmDrawModifier) == 0x4, "");

typedef enum {
	GNM_EMBEDDED_VSH_FULLSCREEN = 0,
} GnmEmbeddedVsShader;

typedef enum {
	GNM_EMBEDDED_PSH_DUMMY = 0,
	GNM_EMBEDDED_PSH_DUMMY_RG32 = 1,
} GnmEmbeddedPsShader;

typedef enum {
	GNM_CACHE_FLUSH_TS = 0x4,
	GNM_CACHE_FLUSH_AND_INV_TS_EVENT = 0x14,
	GNM_BOTTOM_OF_PIPE_TS = 0x28,
	GNM_FLUSH_AND_INV_CB_DATA_TS = 0x2d,
	GNM_CS_DONE = 0x2f,
	GNM_PS_DONE = 0x30,
} GnmEventType;

typedef enum {
	GNM_DATA_SEL_DISCARD = 0x0,
	GNM_DATA_SEL_SEND_DATA32 = 0x1,
	GNM_DATA_SEL_SEND_DATA64 = 0x2,
	GNM_DATA_SEL_SEND_SYS_CLOCK = 0x3,
	GNM_DATA_SEL_SEND_GPU_CLOCK = 0x4,
} GnmEventDataSel;

typedef enum {
	GNM_FACE_CCW = 0x0,
	GNM_FACE_CW = 0x1,
} GnmFaceOrientation;

typedef enum {
	GNM_FILL_POINTS = 0x0,
	GNM_FILL_WIREFRAME = 0x1,
	GNM_FILL_SOLID = 0x2,
} GnmFillMode;

typedef enum {
	GNM_FILTER_POINT = 0x0,
	GNM_FILTER_BILINEAR = 0x1,
	GNM_FILTER_ANISO_POINT = 0x2,
	GNM_FILTER_ANISO_BILINEAR = 0x3,
} GnmFilter;

typedef enum {
	GNM_FILTER_MODE_BLEND = 0x0,
	GNM_FILTER_MODE_MIN = 0x1,
	GNM_FILTER_MODE_MAX = 0x2,
} GnmFilterMode;

typedef enum {
	GNM_GPU_BASE = 0x0,
	GNM_GPU_NEO = 0x1,
} GnmGpuMode;

typedef enum {
	GNM_IMG_DATA_FORMAT_INVALID = 0x0,
	GNM_IMG_DATA_FORMAT_8 = 0x1,
	GNM_IMG_DATA_FORMAT_16 = 0x2,
	GNM_IMG_DATA_FORMAT_8_8 = 0x3,
	GNM_IMG_DATA_FORMAT_32 = 0x4,
	GNM_IMG_DATA_FORMAT_16_16 = 0x5,
	GNM_IMG_DATA_FORMAT_10_11_11 = 0x6,
	GNM_IMG_DATA_FORMAT_11_11_10 = 0x7,
	GNM_IMG_DATA_FORMAT_10_10_10_2 = 0x8,
	GNM_IMG_DATA_FORMAT_2_10_10_10 = 0x9,
	GNM_IMG_DATA_FORMAT_8_8_8_8 = 0xa,
	GNM_IMG_DATA_FORMAT_32_32 = 0xb,
	GNM_IMG_DATA_FORMAT_16_16_16_16 = 0xc,
	GNM_IMG_DATA_FORMAT_32_32_32 = 0xd,
	GNM_IMG_DATA_FORMAT_32_32_32_32 = 0xe,
	GNM_IMG_DATA_FORMAT_5_6_5 = 0x10,
	GNM_IMG_DATA_FORMAT_1_5_5_5 = 0x11,
	GNM_IMG_DATA_FORMAT_5_5_5_1 = 0x12,
	GNM_IMG_DATA_FORMAT_4_4_4_4 = 0x13,
	GNM_IMG_DATA_FORMAT_8_24 = 0x14,
	GNM_IMG_DATA_FORMAT_24_8 = 0x15,
	GNM_IMG_DATA_FORMAT_X24_8_32 = 0x16,
	GNM_IMG_DATA_FORMAT_GB_GR = 0x20,
	GNM_IMG_DATA_FORMAT_BG_RG = 0x21,
	GNM_IMG_DATA_FORMAT_5_9_9_9 = 0x22,
	GNM_IMG_DATA_FORMAT_BC1 = 0x23,
	GNM_IMG_DATA_FORMAT_BC2 = 0x24,
	GNM_IMG_DATA_FORMAT_BC3 = 0x25,
	GNM_IMG_DATA_FORMAT_BC4 = 0x26,
	GNM_IMG_DATA_FORMAT_BC5 = 0x27,
	GNM_IMG_DATA_FORMAT_BC6 = 0x28,
	GNM_IMG_DATA_FORMAT_BC7 = 0x29,
	GNM_IMG_DATA_FORMAT_FMASK8_S2_F1 = 0x2c,
	GNM_IMG_DATA_FORMAT_FMASK8_S4_F1 = 0x2d,
	GNM_IMG_DATA_FORMAT_FMASK8_S8_F1 = 0x2e,
	GNM_IMG_DATA_FORMAT_FMASK8_S2_F2 = 0x2f,
	GNM_IMG_DATA_FORMAT_FMASK8_S4_F2 = 0x30,
	GNM_IMG_DATA_FORMAT_FMASK8_S4_F4 = 0x31,
	GNM_IMG_DATA_FORMAT_FMASK16_S16_F1 = 0x32,
	GNM_IMG_DATA_FORMAT_FMASK16_S8_F2 = 0x33,
	GNM_IMG_DATA_FORMAT_FMASK32_S16_F2 = 0x34,
	GNM_IMG_DATA_FORMAT_FMASK32_S8_F4 = 0x35,
	GNM_IMG_DATA_FORMAT_FMASK32_S8_F8 = 0x36,
	GNM_IMG_DATA_FORMAT_FMASK64_S16_F4 = 0x37,
	GNM_IMG_DATA_FORMAT_FMASK64_S16_F8 = 0x38,
	GNM_IMG_DATA_FORMAT_4_4 = 0x39,
	GNM_IMG_DATA_FORMAT_6_5_5 = 0x3a,
	GNM_IMG_DATA_FORMAT_1 = 0x3b,
	GNM_IMG_DATA_FORMAT_1_REVERSED = 0x3c,
	GNM_IMG_DATA_FORMAT_32_AS_8 = 0x3d,
	GNM_IMG_DATA_FORMAT_32_AS_8_8 = 0x3e,
	GNM_IMG_DATA_FORMAT_32_AS_32_32_32_32 = 0x3f,
} GnmImageFormat;

typedef enum {
	GNM_IMG_NUM_FORMAT_UNORM = 0x0,
	GNM_IMG_NUM_FORMAT_SNORM = 0x1,
	GNM_IMG_NUM_FORMAT_USCALED = 0x2,
	GNM_IMG_NUM_FORMAT_SSCALED = 0x3,
	GNM_IMG_NUM_FORMAT_UINT = 0x4,
	GNM_IMG_NUM_FORMAT_SINT = 0x5,
	GNM_IMG_NUM_FORMAT_SNORM_OGL = 0x6,
	GNM_IMG_NUM_FORMAT_FLOAT = 0x7,
	GNM_IMG_NUM_FORMAT_SRGB = 0x9,
	GNM_IMG_NUM_FORMAT_UBNORM = 0xa,
	GNM_IMG_NUM_FORMAT_UBNORM_OGL = 0xb,
	GNM_IMG_NUM_FORMAT_UBINT = 0xc,
	GNM_IMG_NUM_FORMAT_UBSCALED = 0xd,
} GnmImgNumFormat;

typedef enum {
	GNM_INDEX_16 = 0x0,
	GNM_INDEX_32 = 0x1,
} GnmIndexSize;

typedef enum {
	GNM_SURF_MACRO_ASPECT_1 = 0x0,
	GNM_SURF_MACRO_ASPECT_2 = 0x1,
	GNM_SURF_MACRO_ASPECT_4 = 0x2,
	GNM_SURF_MACRO_ASPECT_8 = 0x3,
} GnmMacroTileAspect;

typedef enum {
	GNM_MACROTILEMODE_1x4_16 = 0x0,
	GNM_MACROTILEMODE_1x2_16 = 0x1,
	GNM_MACROTILEMODE_1x1_16 = 0x2,
	GNM_MACROTILEMODE_1x1_16_DUP = 0x3,
	GNM_MACROTILEMODE_1x1_8 = 0x4,
	GNM_MACROTILEMODE_1x1_4 = 0x5,
	GNM_MACROTILEMODE_1x1_2 = 0x6,
	GNM_MACROTILEMODE_1x1_2_DUP = 0x7,
	GNM_MACROTILEMODE_1x8_16 = 0x8,
	GNM_MACROTILEMODE_1x4_16_DUP = 0x9,
	GNM_MACROTILEMODE_1x2_16_DUP = 0xa,
	GNM_MACROTILEMODE_1x1_16_DUP2 = 0xb,
	GNM_MACROTILEMODE_1x1_8_DUP = 0xc,
	GNM_MACROTILEMODE_1x1_4_DUP = 0xd,
	GNM_MACROTILEMODE_1x1_2_DUP2 = 0xe,
	GNM_MACROTILEMODE_1x1_2_DUP3 = 0xf,
} GnmMacroTileMode;

typedef enum {
	GNM_SURF_DISPLAY_MICRO_TILING = 0x0,
	GNM_SURF_THIN_MICRO_TILING = 0x1,
	GNM_SURF_DEPTH_MICRO_TILING = 0x2,
	GNM_SURF_ROTATED_MICRO_TILING = 0x3,
	GNM_SURF_THICK_MICRO_TILING = 0x4,
} GnmMicroTileMode;

typedef enum {
	GNM_MIPFILTER_NONE = 0x0,
	GNM_MIPFILTER_POINT = 0x1,
	GNM_MIPFILTER_LINEAR = 0x2,
} GnmMipFilter;

typedef enum {
	GNM_SURF_2_BANK = 0x0,
	GNM_SURF_4_BANK = 0x1,
	GNM_SURF_8_BANK = 0x2,
	GNM_SURF_16_BANK = 0x3,
} GnmNumBanks;

typedef enum {
	GNM_ADDR_SURF_P2 = 0x0,
	GNM_ADDR_SURF_P4_8x16 = 0x4,
	GNM_ADDR_SURF_P4_16x16 = 0x5,
	GNM_ADDR_SURF_P4_16x32 = 0x6,
	GNM_ADDR_SURF_P4_32x32 = 0x7,
	GNM_ADDR_SURF_P8_16x16_8x16 = 0x8,
	GNM_ADDR_SURF_P8_16x32_8x16 = 0x9,
	GNM_ADDR_SURF_P8_32x32_8x16 = 0xa,
	GNM_ADDR_SURF_P8_16x32_16x16 = 0xb,
	GNM_ADDR_SURF_P8_32x32_16x16 = 0xc,
	GNM_ADDR_SURF_P8_32x32_16x32 = 0xd,
	GNM_ADDR_SURF_P8_32x64_32x32 = 0xe,
	GNM_ADDR_SURF_P16_32x32_8x16 = 0x10,
	GNM_ADDR_SURF_P16_32x32_16x16 = 0x11,
} GnmPipeConfig;

typedef enum {
	GNM_PT_NONE = 0x0,
	GNM_PT_POINTLIST = 0x1,
	GNM_PT_LINELIST = 0x2,
	GNM_PT_LINESTRIP = 0x3,
	GNM_PT_TRILIST = 0x4,
	GNM_PT_TRIFAN = 0x5,
	GNM_PT_TRISTRIP = 0x6,
	GNM_PT_PATCH = 0x9,
	GNM_PT_LINELIST_ADJ = 0xa,
	GNM_PT_LINESTRIP_ADJ = 0xb,
	GNM_PT_TRILIST_ADJ = 0xc,
	GNM_PT_TRIPSTRIP_ADJ = 0xd,
	GNM_PT_TRI_WITH_WFLAGS = 0x10,
	GNM_PT_RECTLIST = 0x11,
	GNM_PT_LINELOOP = 0x12,
	GNM_PT_QUADLIST = 0x13,
	GNM_PT_QUADSTRIP = 0x14,
	GNM_PT_POLYGON = 0x15,
} GnmPrimitiveType;

typedef enum {
	GNM_PROVOKINGVTX_FIRST = 0x0,
	GNM_PROVOKINGVTX_LAST = 0x1,
} GnmProvokingVertex;

typedef enum {
	GNM_QM_16_8_FIXED_POINT_1_16TH = 0,
	GNM_QM_16_8_FIXED_POINT_1_8TH = 1,
	GNM_QM_16_8_FIXED_POINT_1_4TH = 2,
	GNM_QM_16_8_FIXED_POINT_1_2 = 3,
	GNM_QM_16_8_FIXED_POINT_1 = 4,
	GNM_QM_16_8_FIXED_POINT_1_256TH = 5,
	GNM_QM_14_10_FIXED_POINT_1_1024TH = 6,
	GNM_QM_12_12_FIXED_POINT_1_4096TH = 7,
} GnmQuantMode;

typedef enum {
	GNM_MEMORY_READONLY = 0x10,
	GNM_MEMORY_PRIVATE = 0x60,
	GNM_MEMORY_CACHE_UNCOHERENT = 0x6d,
	GNM_MEMORY_CACHE_COHERENT = 0x6e,
	GNM_MEMORY_UNCACHED = 0x6f,
} GnmMemoryType;

typedef enum {
	GNM_RM_TRUNCATE = 0,
	GNM_RM_ROUND = 1,
	GNM_RM_ROUND_TO_EVEN = 2,
	GNM_RM_ROUND_TO_ODD = 3,
} GnmRoundMode;

typedef enum {
	GNM_ADDR_SAMPLE_SPLIT_1 = 0x0,
	GNM_ADDR_SAMPLE_SPLIT_2 = 0x1,
	GNM_ADDR_SAMPLE_SPLIT_4 = 0x2,
	GNM_ADDR_SAMPLE_SPLIT_8 = 0x3,
} GnmSampleSplit;

typedef enum {
	GNM_STAGE_CS = 0x0,
	GNM_STAGE_PS = 0x1,
	GNM_STAGE_VS = 0x2,
	GNM_STAGE_GS = 0x3,
	GNM_STAGE_ES = 0x4,
	GNM_STAGE_HS = 0x5,
	GNM_STAGE_LS = 0x6,
} GnmShaderStage;

typedef enum {
	GNM_STENCIL_INVALID = 0x0,
	GNM_STENCIL_8 = 0x1,
} GnmStencilFormat;

typedef enum {
	GNM_NUMBER_UNORM = 0x0,
	GNM_NUMBER_SNORM = 0x1,
	GNM_NUMBER_UINT = 0x4,
	GNM_NUMBER_SINT = 0x5,
	GNM_NUMBER_SRGB = 0x6,
	GNM_NUMBER_FLOAT = 0x7,
} GnmSurfaceNumber;

typedef enum {
	GNM_SWAP_STD = 0x0,
	GNM_SWAP_ALT = 0x1,
	GNM_SWAP_STD_REV = 0x2,
	GNM_SWAP_ALT_REV = 0x3,
} GnmSurfaceSwap;

typedef enum {
	GNM_TEX_CLAMP_WRAP = 0x0,
	GNM_TEX_CLAMP_MIRROR = 0x1,
	GNM_TEX_CLAMP_CLAMP_LAST_TEXEL = 0x2,
	GNM_TEX_CLAMP_MIRROR_ONCE_LAST_TEXEL = 0x3,
	GNM_TEX_CLAMP_CLAMP_HALF_BORDER = 0x4,
	GNM_TEX_CLAMP_MIRROR_ONCE_HALF_BORDER = 0x5,
	GNM_TEX_CLAMP_CLAMP_BORDER = 0x6,
	GNM_TEX_CLAMP_MIRROR_ONCE_BORDER = 0x7,
} GnmTexClamp;

typedef enum {
	GNM_TEX_PERFMOD_NONE = 0x0,
	GNM_TEX_PERFMOD_MIN = 0x1,
	GNM_TEX_PERFMOD_DEFAULT = 0x4,
	GNM_TEX_PERFMOD_MAX = 0x7,
} GnmTexPerfModulation;

typedef enum {
	GNM_TEXTURE_1D = 0x8,
	GNM_TEXTURE_2D = 0x9,
	GNM_TEXTURE_3D = 0xa,
	GNM_TEXTURE_CUBEMAP = 0xb,
	GNM_TEXTURE_1D_ARRAY = 0xc,
	GNM_TEXTURE_2D_ARRAY = 0xd,
	GNM_TEXTURE_2D_MSAA = 0xe,
	GNM_TEXTURE_2D_ARRAY_MSAA = 0xf,
} GnmTextureType;

typedef enum {
	GNM_TM_DEPTH_2D_THIN_64 = 0x0,
	GNM_TM_DEPTH_2D_THIN_128 = 0x1,
	GNM_TM_DEPTH_2D_THIN_256 = 0x2,
	GNM_TM_DEPTH_2D_THIN_512 = 0x3,
	GNM_TM_DEPTH_2D_THIN_1K = 0x4,
	GNM_TM_DEPTH_1D_THIN = 0x5,
	GNM_TM_DEPTH_2D_THIN_PRT_256 = 0x6,
	GNM_TM_DEPTH_2D_THIN_PRT_1K = 0x7,

	GNM_TM_DISPLAY_LINEAR_ALIGNED = 0x8,
	GNM_TM_DISPLAY_1D_THIN = 0x9,
	GNM_TM_DISPLAY_2D_THIN = 0xa,
	GNM_TM_DISPLAY_THIN_PRT = 0xb,
	GNM_TM_DISPLAY_2D_THIN_PRT = 0xc,

	GNM_TM_THIN_1D_THIN = 0xd,
	GNM_TM_THIN_2D_THIN = 0xe,
	GNM_TM_THIN_3D_THIN = 0xf,
	GNM_TM_THIN_THIN_PRT = 0x10,
	GNM_TM_THIN_2D_THIN_PRT = 0x11,
	GNM_TM_THIN_3D_THIN_PRT = 0x12,

	GNM_TM_THICK_1D_THICK = 0x13,
	GNM_TM_THICK_2D_THICK = 0x14,
	GNM_TM_THICK_3D_THICK = 0x15,
	GNM_TM_THICK_THICK_PRT = 0x16,
	GNM_TM_THICK_2D_THICK_PRT = 0x17,
	GNM_TM_THICK_3D_THICK_PRT = 0x18,
	GNM_TM_THICK_2D_XTHICK = 0x19,
	GNM_TM_THICK_3D_XTHICK = 0x1a,

	GNM_TM_DISPLAY_LINEAR_GENERAL = 0x1f,
} GnmTileMode;

typedef enum {
	GNM_SURF_TILE_SPLIT_64B = 0x0,
	GNM_SURF_TILE_SPLIT_128B = 0x1,
	GNM_SURF_TILE_SPLIT_256B = 0x2,
	GNM_SURF_TILE_SPLIT_512B = 0x3,
	GNM_SURF_TILE_SPLIT_1KB = 0x4,
	GNM_SURF_TILE_SPLIT_2KB = 0x5,
	GNM_SURF_TILE_SPLIT_4KB = 0x6,
} GnmTileSplit;

typedef enum {
	GNM_WAIT_REG_MEM_FUNC_ALWAYS = 0,
	GNM_WAIT_REG_MEM_FUNC_LESS = 1,
	GNM_WAIT_REG_MEM_FUNC_LESS_EQUAL = 2,
	GNM_WAIT_REG_MEM_FUNC_EQUAL = 3,
	GNM_WAIT_REG_MEM_FUNC_NOT_EQUAL = 4,
	GNM_WAIT_REG_MEM_FUNC_GREATER_EQUAL = 5,
	GNM_WAIT_REG_MEM_FUNC_GREATER = 6,
} GnmWaitRegMemFunc;

typedef enum {
	GNM_ZFILTER_NONE = 0x0,
	GNM_ZFILTER_POINT = 0x1,
	GNM_ZFILTER_LINEAR = 0x2,
} GnmZFilter;

typedef enum {
	GNM_Z_INVALID = 0x0,
	GNM_Z_16 = 0x1,
	GNM_Z_24 = 0x2,
	GNM_Z_32_FLOAT = 0x3,
} GnmZFormat;

#endif	// _GNM_TYPES_H_
