#include "ChonkyNet.hpp"
#include <Common.hpp>
#include <ChonkyNetPackets.hpp>
#include <Loaders/App.hpp>


extern App g_app;

namespace PSN {

using asio::ip::tcp;
using namespace ChonkyNet;

/*
Example sequence for login packet

    using namespace ChonkyNet;
    PacketHeader header;
    LoginPacket pkt;

    header.size = sizeof(pkt);
    header.type = PacketType::Login;
    pkt.client_version = CHONKYNET_VERSION;
    std::strcpy(pkt.username, "ChonkyStation4");
    std::strcpy(pkt.password, "aaaa");

    asio::write(socket, asio::buffer(&header, sizeof(header)));
    asio::write(socket, asio::buffer(&pkt, sizeof(pkt)));

    LoginResponse res;
    asio::read(socket, asio::buffer(&res, sizeof(res)));

    printf("error: %d\n", res.header.err);
    printf("session_token: %s\n", res.session_token);
*/

// Establish TCP connection with server
void ChonkyNetProvider::init() {
    // Create socket
    sock = std::make_unique<tcp::socket>(io);

    // Connect to server
    // TODO: Make it configurable
    sock->connect(tcp::endpoint(asio::ip::make_address("127.0.0.1"), 12345));
}

// Login using a previously generated session token.
// The session token will be generated by the launcher.
// Returns true on successful login
bool ChonkyNetProvider::login(PS4::OS::User::User* user) {
    const auto session_path = user->getHomeDir() / "chonkynet_session";

    if (!fs::exists(session_path))
        return false;

    // The session file contains two lines.
    // The first is the online ID (username), the second is the session token.
    std::ifstream file(session_path);
    std::string online_id;
    std::string token;
    if (!std::getline(file, online_id) || !std::getline(file, token)) {
        return false;
    }

    // Send AuthorizeSession packet
    PacketHeader header;
    AuthorizeSessionPacket pkt;
    header.size = sizeof(pkt);
    header.type = PacketType::AuthorizeSession;

    pkt.client_version = CHONKYNET_VERSION;
    std::strncpy(pkt.username, online_id.c_str(), 16);
    std::strncpy(pkt.session_token, token.c_str(), CHONKYNET_SESSION_TOKEN_LENGTH);

    asio::write(*sock, asio::buffer(&header, sizeof(header)));
    asio::write(*sock, asio::buffer(&pkt, sizeof(pkt)));

    // Wait for response
    AuthorizeSessionResponse res;
    asio::read(*sock, asio::buffer(&res, sizeof(res)));

    if (res.header.err != CHONKYNET_OK)
        return false;

    user->is_logged_in_psn = true;
    user->online_id = online_id;
    user->account_id = res.account_id;

    printf("Logged in as %s\n", online_id.c_str());
    return true;
}

void ChonkyNetProvider::getRankingByRangeAsync(SceNpRequest* req, SceNpScoreBoardId board_id, SceNpScoreRankNumber start_rank, SceNpScoreRankDataA* rank_array, size_t n_ranks, SceNpScoreComment* comment_array, size_t n_comments, SceNpScoreGameInfo* info_array, size_t n_info, size_t n_array, SceRtcTick* last_sort_date, SceNpScoreRankNumber* n_total_ranks) {
    std::thread([=]() {
        PacketHeader header;
        GetRankingByRangePacket pkt;
        header.size = sizeof(pkt);
        header.type = PacketType::GetRankingByRange;

        std::strncpy(pkt.title_id, g_app.title_id.c_str(), sizeof(pkt.title_id));
        pkt.board_id = board_id;
        pkt.starting_rank = start_rank;
        pkt.n_ranks = n_array;

        asio::write(*sock, asio::buffer(&header, sizeof(header)));
        asio::write(*sock, asio::buffer(&pkt, sizeof(pkt)));

        // Wait for response
        GetRankingByRangeResponse res;
        asio::read(*sock, asio::buffer(&res, sizeof(res)));
        if (res.header.err != CHONKYNET_OK) {
            printf("getRankingByRangeAsync: server returned error %d\n", res.header.err);
            return;
        }

        printf("total ranks %d, obtained %d\n", res.n_total_ranks, res.n_obtained_ranks);

        std::vector<RankingInfo> rankings;
        int to_receive = res.n_obtained_ranks;
        while (to_receive--) {
            RankingInfo info;
            asio::read(*sock, asio::buffer(&info, sizeof(info)));
            printf("rank %d, score %d, id %s\n", info.rank, info.score, info.online_id);
            rankings.push_back(info);
        }
        
        *n_total_ranks = res.n_total_ranks;

        const auto to_obtain = std::min(res.n_obtained_ranks, n_array);
        for (int i = 0; i < to_obtain; i++) {
            rank_array[i].account_id = 100;
            std::strncpy(rank_array[i].online_id.data, rankings[i].online_id, 16);
            rank_array[i].rank = rankings[i].rank;
            rank_array[i].serial_rank = 1;
            rank_array[i].highest_rank = rankings[i].highest_rank;
            rank_array[i].score_value = rankings[i].score;
        }

        req->finish(SCE_OK);

    }).detach();
}

void ChonkyNetProvider::recordScoreAsync(SceNpRequest* req, SceNpScoreBoardId board_id, SceNpScoreValue score, const SceNpScoreComment* comment, const SceNpScoreGameInfo* game_info, SceNpScoreRankNumber* tmp_rank, const SceRtcTick* compare_date) {
    std::thread([=]() {
        PacketHeader header;
        RecordScorePacket pkt;
        header.size = sizeof(pkt);
        header.type = PacketType::RecordScore;

        std::strncpy(pkt.title_id, g_app.title_id.c_str(), sizeof(pkt.title_id));
        pkt.board_id = board_id;
        pkt.score = score;
        pkt.account_id = PS4::OS::User::current->account_id;    // TODO: Store current user in provider class?

        asio::write(*sock, asio::buffer(&header, sizeof(header)));
        asio::write(*sock, asio::buffer(&pkt, sizeof(pkt)));

        // Wait for response
        RecordScoreResponse res;
        asio::read(*sock, asio::buffer(&res, sizeof(res)));
        if (res.header.err != CHONKYNET_OK) {
            printf("recordScoreAsync: server returned error %d\n", res.header.err);
            return;
        }

        req->finish(SCE_OK);

    }).detach();
}

}   // End namespace PSN